### ISSUE TITLE
没有keystore

### ISSUE THREAD

**Issue by zhouzhixue** [zhan2046/awaker#1]

**Comment by zhan2046** [comment]
@zhouzhixue  你可以在android studio自己做一个，我的是需要上传到应用市场的

或者你把app下的build.gradle:

    buildTypes {

        debug {
            // 为了不和 release 版本冲突
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.config
        }

去掉这一行：  signingConfig signingConfigs.config
