### ISSUE TITLE
可以提供一下api接口数据吗方便学习，老是报token无效

### ISSUE THREAD

**Issue by leixiongbo** [zhan2046/awaker#12]

**Comment by zhan2046** [comment]
可以使用charles抓包工具抓取接口数据，每个请求需要带一个token，抓包抓得到，代码里查看也是可以的
https://github.com/ruzhan123/awaker/blob/master/app/src/main/java/com/future/awaker/base/viewmodel/BaseViewModel.java
@leixiongbo
