### ISSUE TITLE
build.gradle里两个compile 'com.afollestad.material-dialogs:core:0.9.4.5'   0.9.4.6，啥意思？

### ISSUE THREAD

**Issue by cxmmxc** [zhan2046/awaker#3]
compile 'com.afollestad.material-dialogs:core:0.9.4.5'

compile 'com.afollestad.material-dialogs:core:0.9.4.6'

**Comment by zhan2046** [comment]
之前忘记删除了，我删除先

**Comment by zhan2046** [comment]
@cxmmxc 眼神亮噢
